spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/your-db?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false
    username: username
    password: password

  batch:
    job:
      enabled: false # 서버 재시작시 배치 자동실행 방지
    jdbc:
      initialize-schema: always